name: Docs

on:
  push:
    branches:
      - master

jobs:
  release_sphinx:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    name: "Publish Sphinx"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      if: github.event_name == 'push' && github.repository == 'psi4/psi4docs' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/master' )
      with:
        branch: gh-pages
        folder: sphinxman
